baseURL = 'https://github.com/shdynila/0_ath_wiki'
languageCode = 'en-us'
title = '0ath MMORPG Knowledge Base'
theme = 'PaperMod'

[params]
  env = 'production'
  description = 'Devlog and Documentation for the 0ath MMORPG'
  author = '0ath Dev'
  ShowToc = true
  TocOpen = true
